language: r
r:
  - bioc-devel
sudo: required
os: linux
dist: bionic
cache: packages
addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - libxml2-dev
bioc_required: true
warnings_are_errors: false
r_check_args: "--no-build-vignettes --no-vignettes"
r_build_args: "--no-build-vignettes"
r_packages:
  - covr
  - shiny
  - testthat
after_success:
  - Rscript -e 'library(covr); codecov()'
