language: r
r: bioc-devel
sudo: required
dist: trusty
cache: packages
addons:
  apt:
    packages:
      - libusb-1.0-0-dev
bioc_required: true
warnings_are_errors: false
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
